#!/bin/bash

TMP_DIR=tmp-licenses
mkdir -p ${TMP_DIR}
cd ${TMP_DIR}

OSI_API=https://opensource.org/api
OSI_LICENSES=${OSI_API}/licenses

if [ "$1" != "" ]
then
    DEBUG=true
fi

err()
{
    if [ "$DEBUG" != "" ]
    then
        echo "$*" 1>&2
    fi
}

verbose()
{
    err "$*"
}

download()
{
    URL="$1"
    INDENT="$2"
    FILE="$(basename $URL)"
    
    verbose "${INDENT}Download \"$URL\""
    if [ -f "${FILE}" ]
    then
        verbose "${INDENT}  * \"$FILE\" already exists, not downloading $URL"
        return
    fi
    
    verbose "${INDENT}  * downloading \"$URL\""
    curl -s -LJO "${URL}"
    if [ $? -ne 0 ]
    then
        err "Failed downloading \"$URL\""
        exit 1
    fi
}

check_foss_licenses_helper()
{
    ALIAS="$1"
    EXPECTED="$2"
    ACTUAL=$(../devel/flame -of text license "$ALIAS")

    if [ "${EXPECTED}" != "${ACTUAL}" ]
    then
        verbose "      missing: ${ALIAS} ${EXPECTED}"
        echo "${ALIAS} : ${EXPECTED}"
    else
        verbose "      already present: ${ALIAS} ${EXPECTED}"
    fi
}

check_foss_licenses()
{
    LICENSE_ID="$1"
    LICENSE_SPDX_ID="$2"
    LICENSE_NAME="$3"
    verbose "     Checking $LICENSE_ID"

    check_foss_licenses_helper "$LICENSE_ID" "${LICENSE_SPDX_ID}"
}

check_license()
{
    LICENSE_ID="$1"
    verbose "  * Check license: $LICENSE_ID"
    OSI_LICENSE="${OSI_API}/license/$LICENSE_ID"

    download "${OSI_LICENSE}" "    "
    LICENSE_FILE="$(basename ${OSI_LICENSE})"

    LICENSE_SPDX_ID="$(cat $LICENSE_FILE | jq -r .spdx_id)"
    LICENSE_NAME="$(cat $LICENSE_FILE | jq -r .name)"

    check_foss_licenses "$LICENSE_ID" "$LICENSE_SPDX_ID" "$LICENSE_NAME"
}

license_list()
{
    verbose "Looping over all licenses"
    LICENSE_FILE="$(basename $OSI_LICENSES)"
    cat "${LICENSE_FILE}"  | \
        jq -r .[].id  | \
        while read LICENSE
        do
            check_license "${LICENSE}"
        done
}


download "$OSI_LICENSES"
license_list

